SELECT
  *
FROM BATCH_JOB_INSTANCE
GO
SELECT
  *
FROM BATCH_JOB_EXECUTION
GO
SELECT
  *
FROM BATCH_JOB_EXECUTION_PARAMS
GO
SELECT
  *
FROM BATCH_JOB_EXECUTION_CONTEXT
GO
SELECT
  *
FROM BATCH_STEP_EXECUTION
GO
SELECT
  *
FROM BATCH_STEP_EXECUTION_CONTEXT
GO
/*
delete from dbo.BATCH_JOB_EXECUTION_PARAMS
go
delete from dbo.BATCH_STEP_EXECUTION_CONTEXT
go
delete from dbo.BATCH_STEP_EXECUTION
go
delete from BATCH_JOB_EXECUTION_CONTEXT
go
delete from batch_job_execution
go
delete from dbo.BATCH_JOB_EXECUTION_SEQ
go
delete from dbo.BATCH_JOB_INSTANCE
go
delete from dbo.BATCH_JOB_SEQ
go
delete from dbo.BATCH_STEP_EXECUTION_SEQ
go
*/